name: her_long_game
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0
dependencies:
  http: ^1.0.0
  cached_network_image: ^3.0.0
  url_launcher: ^6.0.0
  sign_in_with_apple: '>=6.1.2'
  google_sign_in: '>=6.2.1'
  path_provider: ^2.0.0
  share_plus: ^12.0.0
  supabase_flutter: '>=1.10.0'
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: any
  go_router: ^16.2.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/Social_Media_Kit-Her_Long_Game_Instagram-Profile.jpg
    - assets/images/Her_Long_Game-02.jpg
    - assets/documents/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icons/dreamflow_icon.jpg
  remove_alpha_ios: true
